In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\Shadab\\OneDrive\\Desktop\\digital_marketing_campaign_dataset.csv")
df.head()

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion
0,8000,56,Female,136912,Social Media,Awareness,6497.870068,0.043919,0.088031,0,2.399017,7.396803,19,6,9,4,688,IsConfid,ToolConfid,1
1,8001,69,Male,41760,Email,Retention,3898.668606,0.155725,0.182725,42,2.917138,5.352549,5,2,7,2,3459,IsConfid,ToolConfid,1
2,8002,46,Female,88456,PPC,Awareness,1546.429596,0.277490,0.076423,2,8.223619,13.794901,0,11,2,8,2337,IsConfid,ToolConfid,1
3,8003,32,Female,44085,PPC,Conversion,539.525936,0.137611,0.088004,47,4.540939,14.688363,89,2,2,0,2463,IsConfid,ToolConfid,1
4,8004,60,Female,83964,PPC,Conversion,1678.043573,0.252851,0.109940,0,2.046847,13.993370,6,6,6,8,4345,IsConfid,ToolConfid,1

In [3]:
df.describe(include="all")

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion
count,8000.00000,8000.000000,8000,8000.000000,8000,8000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000,8000,8000.000000
unique,NaN,NaN,2,NaN,5,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN
top,NaN,NaN,Female,NaN,Referral,Conversion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IsConfid,ToolConfid,NaN
freq,NaN,NaN,4839,NaN,1719,2077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000,8000,NaN
mean,11999.50000,43.625500,NaN,84664.196750,NaN,NaN,5000.944830,0.154829,0.104389,24.751625,5.549299,7.727718,49.799750,9.476875,4.467375,4.485500,2490.268500,NaN,NaN,0.876500
std,2309.54541,14.902785,NaN,37580.387945,NaN,NaN,2838.038153,0.084007,0.054878,14.312269,2.607358,4.228218,28.901165,5.711111,2.856564,2.888093,1429.527162,NaN,NaN,0.329031
min,8000.00000,18.000000,NaN,20014.000000,NaN,NaN,100.054813,0.010005,0.010018,0.000000,1.000428,0.501669,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000
25%,9999.75000,31.000000,NaN,51744.500000,NaN,NaN,2523.221165,0.082635,0.056410,13.000000,3.302479,4.068340,25.000000,5.000000,2.000000,2.000000,1254.750000,NaN,NaN,1.000000
50%,11999.50000,43.000000,NaN,84926.500000,NaN,NaN,5013.440044,0.154505,0.104046,25.000000,5.534257,7.682956,50.000000,9.000000,4.000000,4.000000,2497.000000,NaN,NaN,1.000000
75%,13999.25000,56.000000,NaN,116815.750000,NaN,NaN,7407.989369,0.228207,0.152077,37.000000,7.835756,11.481468,75.000000,14.000000,7.000000,7.000000,3702.250000,NaN,NaN,1.000000
max,15999.00000,69.000000,NaN,149986.000000,NaN,NaN,9997.914781,0.299968,0.199995,49.000000,9.999055,14.995311,99.000000,19.000000,9.000000,9.000000,4999.000000,NaN,NaN,1.000000

In [4]:
df.isnull().sum()

CustomerID             0
Age                    0
Gender                 0
Income                 0
CampaignChannel        0
CampaignType           0
AdSpend                0
ClickThroughRate       0
ConversionRate         0
WebsiteVisits          0
PagesPerVisit          0
TimeOnSite             0
SocialShares           0
EmailOpens             0
EmailClicks            0
PreviousPurchases      0
LoyaltyPoints          0
AdvertisingPlatform    0
AdvertisingTool        0
Conversion             0
dtype: int64

In [5]:
df=df.rename(columns={
    'CustomerID':'customer_id',
    'Age':'age',
    'Gender':'gender',
    'Income':'income',
    'CampaignChannel':'campaign_channel',
    'CampaignType':'campaign_type',
    'AdSpend':'ad_spend',
    'ClickThroughRate':'click_through_rate',
    'ConversionRate':'conversion_rate',
    'WebsiteVisits':'website_visits',
    'PagesPerVisit':'pages_per_visit',
    'TimeOnSite':'time_on_site',
    'SocialShares':'social_shares',
    'EmailOpens':'email_opens',
    'EmailClicks':'email_clicks',
    'PreviousPurchases':'previous_purchase',
    'LoyaltyPoints':'loyalty_points',
    'AdvertisingPlatform':'advertising_platform',
    'AdvertisingTool':'advertising_tool',
    'Conversion':'conversion'
})

In [6]:
df.columns

Index(['customer_id', 'age', 'gender', 'income', 'campaign_channel',
       'campaign_type', 'ad_spend', 'click_through_rate', 'conversion_rate',
       'website_visits', 'pages_per_visit', 'time_on_site', 'social_shares',
       'email_opens', 'email_clicks', 'previous_purchase', 'loyalty_points',
       'advertising_platform', 'advertising_tool', 'conversion'],
      dtype='str')

In [7]:
#creating a columns age_group:
labels=['Young Adult', 'Adult', 'Middle Aged', 'Senior']
df['age_group']=pd.qcut(df['age'], q=4, labels=labels)
df[['age_group', 'age']]

        age_group  age
0     Middle Aged   56
1          Senior   69
2     Middle Aged   46
3           Adult   32
4          Senior   60
...           ...  ...
7995  Young Adult   21
7996        Adult   43
7997  Young Adult   28
7998  Young Adult   19
7999  Young Adult   31

[8000 rows x 2 columns]

In [8]:
#creating a columns age_group:
labels=['Young Adult', 'Adult', 'Middle Aged', 'Senior']
df['age_group']=pd.qcut(df['age'], q=4, labels=labels)
df[['age_group', 'age']]

        age_group  age
0     Middle Aged   56
1          Senior   69
2     Middle Aged   46
3           Adult   32
4          Senior   60
...           ...  ...
7995  Young Adult   21
7996        Adult   43
7997  Young Adult   28
7998  Young Adult   19
7999  Young Adult   31

[8000 rows x 2 columns]

In [9]:
df.groupby('age_group')['age'].agg([min, max])

             min  max
age_group
Young Adult   18   31
Adult         32   43
Middle Aged   44   56
Senior        57   69

In [10]:
#creating a new column income_group:
income_labels=['Low', 'Medium', 'High']
df['income_group']=pd.qcut(df['income'], q=3, labels=income_labels)
df[['income_group', 'income']]

     income_group  income
0            High  136912
1             Low   41760
2          Medium   88456
3             Low   44085
4          Medium   83964
...           ...     ...
7995          Low   24849
7996          Low   44718
7997         High  125471
7998         High  107862
7999       Medium   93002

[8000 rows x 2 columns]

In [11]:
df.groupby('income_group')['income'].agg([min, max])

                 min     max
income_group
Low            20014   63386
Medium         63388  106677
High          106687  149986

In [12]:
df['advertising_platform'].unique()

<ArrowStringArray>
['IsConfid']
Length: 1, dtype: str

In [13]:
df['advertising_tool'].unique()

<ArrowStringArray>
['ToolConfid']
Length: 1, dtype: str

In [14]:
#Both the columns "advertising_platform" and "advertising_tool" contains same value in their each rows.
#I am going to delete them as there's no requirement for those columns for analyzing the data.
df=df.drop('advertising_platform', axis=1)
df=df.drop('advertising_tool', axis=1)

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'income', 'campaign_channel',
       'campaign_type', 'ad_spend', 'click_through_rate', 'conversion_rate',
       'website_visits', 'pages_per_visit', 'time_on_site', 'social_shares',
       'email_opens', 'email_clicks', 'previous_purchase', 'loyalty_points',
       'conversion', 'age_group', 'income_group'],
      dtype='str')

In [16]:
#Renaming the values of the column 'conversion':
df['conversion']=df['conversion'].map({0:'No', 1:'Yes'})
df['conversion']

0       Yes
1       Yes
2       Yes
3       Yes
4       Yes
       ...
7995     No
7996     No
7997    Yes
7998    Yes
7999     No
Name: conversion, Length: 8000, dtype: str

In [17]:
#Exporting Clean Data:
df.to_csv('Digital Marketing Campaign Performance Analysis.csv', index=False)

In [18]:

from sqlalchemy import create_engine
# Defining my database credentials
USER = "root"
PASSWORD = "Sarfu123"
HOST = "127.0.0.1"        
PORT = "3306"             
DATABASE = "Digital_Marketing_Campaign_Performance_Analysis"

# Creating the SQLAlchemy engine connection string
connection_string = f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
engine = create_engine(connection_string)

In [19]:
# Uploading the DataFrame to MySQL
df.to_sql(
    name='table1',        
    con=engine,               
    if_exists='replace',      
    index=False               
)

8000